# Generated by Django 5.2.3 on 2026-06-11 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0004_medical_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Calculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medical')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculate.user')),
            ],
        ),
    ]
