# Generated by Django 5.2.3 on 2026-06-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Tibbi Nümayəndə', 'Tibbi Nümayəndə'), ('Menecer', 'Menecer'), ('Rəhbər', 'Rəhbər')], default='Tibbi Nümayəndə', max_length=100),
        ),
    ]
