# Generated by Django 5.2.3 on 2026-06-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Tibbi Nümayəndə', 'Tibbi Nümayəndə'), ('Menecer', 'Menecer'), ('Rəhbər', 'Rəhbər')], default='Rəhbər', max_length=100),
        ),
    ]
