# Generated by Django 5.2.3 on 2026-06-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(blank=True, choices=[('QRUP 1', 'Qrup 1'), ('QRUP 2', 'Qrup 2')], max_length=100, null=True),
        ),
    ]
