# Generated by Django 5.2.3 on 2026-06-30 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0004_user_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('user_group', models.CharField(blank=True, max_length=50, null=True)),
                ('user_role', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('items', models.JSONField(default=dict)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calculate.user')),
            ],
            options={
                'verbose_name': 'Hesabat',
                'verbose_name_plural': 'Hesabatlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
