# Generated by Django 5.2.5 on 2025-09-11 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(choices=[('baku', 'Bakı'), ('ganja', 'Gəncə'), ('sumqayit', 'Sumqayıt'), ('mingachevir', 'Mingəçevir'), ('shirvan', 'Şirvan'), ('naftalan', 'Naftalan'), ('shamakhi', 'Şamaxı'), ('shusha', 'Şuşa'), ('yevlakh', 'Yevlax'), ('khankendi', 'Xankəndi'), ('khirdalan', 'Xırdalan'), ('lankaran', 'Lənkəran'), ('gazakh', 'Qazax'), ('dashkasan', 'Daşkəsən'), ('goygol', 'Göygöl'), ('goranboy', 'Goranboy'), ('terter', 'Tərtər'), ('zagatala', 'Zaqatala'), ('qakh', 'Qax'), ('oguz', 'Oğuz'), ('guba', 'Quba'), ('khachmaz', 'Xaçmaz'), ('kurdemir', 'Kürdəmir'), ('hajigabul', 'Hacıqabul'), ('sabirabad', 'Sabirabad'), ('saatli', 'Saatlı'), ('imisli', 'İmişli'), ('sabran', 'Şabran'), ('astara', 'Astara'), ('lerik', 'Lerik'), ('yardimli', 'Yardımlı'), ('masalli', 'Masallı'), ('jalilabad', 'Cəlilabad'), ('bilasuvar', 'Biləsuvar'), ('neftchala', 'Neftçala'), ('salyan', 'Salyan'), ('shaki', 'Şəki'), ('zardab', 'Zərdab'), ('agjabadi', 'Ağcabədi'), ('beylagan', 'Beyləqan'), ('fuzuli', 'Füzuli'), ('jabrayil', 'Cəbrayıl'), ('aghdam', 'Ağdam'), ('aghdash', 'Ağdaş'), ('gobustan', 'Qobustan'), ('shabran', 'Şabran'), ('shamkir', 'Şəmkir'), ('gusar', 'Qusar'), ('siyezen', 'Siyəzən'), ('balakan', 'Balakən'), ('samukh', 'Samux'), ('kalbajar', 'Kəlbəcər'), ('lachin', 'Laçın'), ('zangilan', 'Zəngilan'), ('qubadli', 'Qubadlı'), ('aghstafa', 'Ağstafa'), ('tovuz', 'Tovuz'), ('ismayilli', 'İsmayıllı'), ('sheki', 'Şəki'), ('dashkasan', 'Daşkəsən')], max_length=100)),
            ],
            options={
                'verbose_name': 'Şəhər',
                'verbose_name_plural': 'Şəhərlər ',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100, unique=True)),
                ('region_type', models.CharField(blank=True, choices=[('Bakı', 'Bakı'), ('Digər', 'Digər')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Bölgə',
                'verbose_name_plural': 'Bölgələr ',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.city')),
                ('region_net', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.region')),
            ],
            options={
                'verbose_name': 'Xəstəxana/Klinika',
                'verbose_name_plural': 'Xəstəxana/Klinikalar ',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='regions.region'),
        ),
    ]
