# Generated by Django 5.2.5 on 2025-10-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hospital',
            unique_together={('hospital_name', 'region_net')},
        ),
    ]
