# Generated by Django 5.2.3 on 2025-12-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_alter_hospital_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Şəhər', 'verbose_name_plural': 'Şəhərlər'},
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(choices=[('Bakı', 'Bakı'), ('Gəncə', 'Gəncə'), ('Sumqayıt', 'Sumqayıt'), ('Mingəçevir', 'Mingəçevir'), ('Şirvan', 'Şirvan'), ('Naftalan', 'Naftalan'), ('Şamaxı', 'Şamaxı'), ('Şuşa', 'Şuşa'), ('Yevlax', 'Yevlax'), ('Xankəndi', 'Xankəndi'), ('Xırdalan', 'Xırdalan'), ('Lənkəran', 'Lənkəran'), ('Qazax', 'Qazax'), ('Daşkəsən', 'Daşkəsən'), ('Göygöl', 'Göygöl'), ('Goranboy', 'Goranboy'), ('Tərtər', 'Tərtər'), ('Zaqatala', 'Zaqatala'), ('Qax', 'Qax'), ('Oğuz', 'Oğuz'), ('Quba', 'Quba'), ('Xaçmaz', 'Xaçmaz'), ('Kürdəmir', 'Kürdəmir'), ('Hacıqabul', 'Hacıqabul'), ('Sabirabad', 'Sabirabad'), ('Saatlı', 'Saatlı'), ('İmişli', 'İmişli'), ('Şabran', 'Şabran'), ('Astara', 'Astara'), ('Lerik', 'Lerik'), ('Yardımlı', 'Yardımlı'), ('Masallı', 'Masallı'), ('Cəlilabad', 'Cəlilabad'), ('Biləsuvar', 'Biləsuvar'), ('Neftçala', 'Neftçala'), ('Salyan', 'Salyan'), ('Şəki', 'Şəki'), ('Zərdab', 'Zərdab'), ('Ağcabədi', 'Ağcabədi'), ('Beyləqan', 'Beyləqan'), ('Füzuli', 'Füzuli'), ('Cəbrayıl', 'Cəbrayıl'), ('Ağdam', 'Ağdam'), ('Ağdaş', 'Ağdaş'), ('Qobustan', 'Qobustan'), ('Şəmkir', 'Şəmkir'), ('Qusar', 'Qusar'), ('Siyəzən', 'Siyəzən'), ('Balakən', 'Balakən'), ('Samux', 'Samux'), ('Kəlbəcər', 'Kəlbəcər'), ('Laçın', 'Laçın'), ('Zəngilan', 'Zəngilan'), ('Qubadlı', 'Qubadlı'), ('Ağstafa', 'Ağstafa'), ('Tovuz', 'Tovuz'), ('İsmayıllı', 'İsmayıllı')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('region', 'city_name')},
        ),
    ]
