# Generated by Django 5.2.3 on 2026-05-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_alter_city_options_alter_city_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_type',
            field=models.CharField(blank=True, choices=[('Bakı', 'Bakı'), ('Digər', 'Digər'), ('Şəhər', 'Şəhər')], max_length=50, null=True),
        ),
    ]
