# Generated by Django 5.2.3 on 2026-09-08 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Depo dərmanı',
                'verbose_name_plural': 'Depo dərmanları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UploadedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='depo_reports/%Y/%m/')),
                ('title', models.CharField(blank=True, help_text="Məs: 'Solvey Maxpharma — Avqust 2026'. Boş saxlansa fayl adından götürülür.", max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Depo hesabatı',
                'verbose_name_plural': 'Depo hesabatları',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='depo_sales.drug')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='depo_sales.uploadedreport')),
            ],
            options={
                'verbose_name': 'Depo satış qeydi',
                'verbose_name_plural': 'Depo satış qeydləri',
                'indexes': [models.Index(fields=['report', 'drug'], name='depo_sales__report__847567_idx'), models.Index(fields=['report', 'city'], name='depo_sales__report__a37995_idx')],
                'constraints': [models.UniqueConstraint(fields=('report', 'drug', 'city'), name='unique_depo_report_drug_city')],
            },
        ),
    ]
