# Generated by Django 5.2.3 on 2026-05-19 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0008_doctors_is_active'),
        ('medicine', '0002_alter_medical_table'),
        ('regions', '0004_alter_region_region_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Istifadeci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('sifre', models.CharField(max_length=255)),
                ('ad', models.CharField(max_length=150)),
                ('rol', models.CharField(choices=[('numayende', 'Tibbi Nümayəndə'), ('menecer', 'Menecer'), ('rehber', 'Rəhbər')], default='numayende', max_length=20)),
                ('aktiv', models.BooleanField(default=True)),
                ('bolge', models.ForeignKey(blank=True, db_column='bolge_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vizit_istifadeciler', to='regions.region')),
            ],
            options={
                'db_table': 'istifadeciler',
                'ordering': ['rol', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='Vizit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('munasibat', models.CharField(choices=[('Xatırlatma', 'Xatırlatma'), ('Annotasiya', 'Annotasiya'), ('Münasibət', 'Münasibət'), ('İş planı', 'İş planı'), ('Propaqanda', 'Propaqanda')], max_length=20)),
                ('tarix', models.DateField()),
                ('vaxt', models.TimeField()),
                ('qeyd', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bolge', models.ForeignKey(db_column='bolge_id', on_delete=django.db.models.deletion.PROTECT, related_name='vizitler', to='regions.region')),
                ('hekim', models.ForeignKey(db_column='hekim_id', on_delete=django.db.models.deletion.PROTECT, related_name='vizitler', to='doctors.doctors')),
                ('istifadeci', models.ForeignKey(db_column='istifadeci_id', on_delete=django.db.models.deletion.PROTECT, related_name='vizitler', to='vizit.istifadeci')),
                ('rayon', models.ForeignKey(db_column='rayon_id', on_delete=django.db.models.deletion.PROTECT, related_name='vizitler', to='regions.city')),
            ],
            options={
                'db_table': 'vizitler',
            },
        ),
        migrations.CreateModel(
            name='VizitPreparat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparat', models.ForeignKey(db_column='preparat_id', on_delete=django.db.models.deletion.PROTECT, related_name='vizitler', to='medicine.medical')),
                ('vizit', models.ForeignKey(db_column='vizit_id', on_delete=django.db.models.deletion.CASCADE, related_name='preparatlar', to='vizit.vizit')),
            ],
            options={
                'db_table': 'vizit_preparatlar',
            },
        ),
    ]
