# Generated by Django 5.2.3 on 2026-05-19 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_alter_region_region_type'),
        ('vizit', '0002_seed_default_istifadeciler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vizit',
            name='rayon',
            field=models.ForeignKey(blank=True, db_column='rayon_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vizitler', to='regions.city'),
        ),
    ]
