# Generated by Django 5.2.3 on 2026-05-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0003_alter_vizit_rayon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vizit',
            name='munasibat',
            field=models.CharField(choices=[('Xatırlatma', 'Xatırlatma'), ('Annotasiya', 'Annotasiya'), ('Münasibət', 'Münasibət'), ('İş planı', 'İş planı'), ('Propaqanda', 'Propaqanda'), ('Razılaşma', 'Razılaşma')], max_length=20),
        ),
    ]
