# Generated by Django 5.2.3 on 2026-05-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_alter_region_region_type'),
        ('vizit', '0004_alter_vizit_munasibat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='istifadeci',
            name='bolge',
        ),
        migrations.AddField(
            model_name='istifadeci',
            name='bolgeler',
            field=models.ManyToManyField(blank=True, db_table='istifadeci_bolgeleri', related_name='vizit_istifadeciler', to='regions.region'),
        ),
    ]
