# Generated by Django 5.2.3 on 2026-05-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0005_remove_istifadeci_bolge_istifadeci_bolgeler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='istifadeci',
            name='rol',
            field=models.CharField(choices=[('numayende', 'Tibbi Nümayəndə'), ('menecer', 'Menecer'), ('diviziya_rehb', 'Diviziya Rəhbər'), ('rehber', 'Rəhbər')], default='numayende', max_length=20),
        ),
    ]
