# Generated by Django 5.2.3 on 2026-06-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0006_alter_istifadeci_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='vizit',
            name='aptek_ad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
