# Generated by Django 5.2.3 on 2026-06-05 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_medical_in_stock'),
        ('regions', '0004_alter_region_region_type'),
        ('vizit', '0007_vizit_aptek_ad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vizit',
            name='aptek_ad',
        ),
        migrations.CreateModel(
            name='AptekVizit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aptek_ad', models.CharField(max_length=255)),
                ('tarix', models.DateField()),
                ('vaxt', models.TimeField()),
                ('qeyd', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bolge', models.ForeignKey(db_column='bolge_id', on_delete=django.db.models.deletion.PROTECT, related_name='aptek_vizit', to='regions.region')),
                ('rayon', models.ForeignKey(db_column='rayon_id', on_delete=django.db.models.deletion.PROTECT, related_name='aptek_vizit', to='regions.city')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='aptek_vizit', to='vizit.istifadeci')),
            ],
            options={
                'db_table': 'AptekVizit',
            },
        ),
        migrations.CreateModel(
            name='AptekVizitPreparat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorusulub', models.BooleanField(default=False)),
                ('satilib', models.BooleanField(default=False)),
                ('movcuddur', models.BooleanField(default=True)),
                ('aptek_vizit', models.ForeignKey(db_column='aptek_vizit_id', on_delete=django.db.models.deletion.CASCADE, related_name='preparatlar', to='vizit.aptekvizit')),
                ('preparat', models.ForeignKey(db_column='preparat_id', on_delete=django.db.models.deletion.PROTECT, related_name='aptek_vizitler', to='medicine.medical')),
            ],
        ),
    ]
