# Generated by Django 5.2.3 on 2026-06-05 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0008_remove_vizit_aptek_ad_aptekvizit_aptekvizitpreparat'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptekvizit',
            name='aptek_nomre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aptekvizitpreparat',
            name='aptek_iscisi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aptekvizitpreparat',
            name='qeyd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aptekvizitpreparat',
            name='ref_vez',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aptekvizitpreparat',
            name='aptek_vizit',
            field=models.ForeignKey(blank=True, db_column='aptek_vizit_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preparatlar', to='vizit.aptekvizit'),
        ),
    ]
