# Generated by Django 5.2.3 on 2026-06-08 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_doctors_is_active'),
        ('vizit', '0009_aptekvizit_aptek_nomre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vizit',
            name='hekim',
            field=models.ForeignKey(blank=True, db_column='hekim_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vizitler', to='doctors.doctors'),
        ),
    ]
