# Generated by Django 5.2.3 on 2026-06-09 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_alter_region_region_type'),
        ('vizit', '0010_alter_vizit_hekim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptekvizit',
            name='rayon',
            field=models.ForeignKey(blank=True, db_column='rayon_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aptek_vizit', to='regions.city'),
        ),
    ]
