# Generated by Django 5.2.3 on 2026-06-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0011_alter_aptekvizit_rayon'),
    ]

    operations = [
        migrations.AddField(
            model_name='istifadeci',
            name='qrup',
            field=models.CharField(blank=True, choices=[('QRUP 1', 'QRUP 1'), ('QRUP 2', 'QRUP 2')], max_length=20, null=True, verbose_name='Qrup'),
        ),
    ]
