# Generated by Django 5.2.3 on 2026-09-11 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_doctors_is_active'),
        ('medicine', '0004_medical_position'),
        ('regions', '0004_alter_region_region_type'),
        ('vizit', '0012_istifadeci_qrup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dr', models.ForeignKey(blank=True, db_column='dr_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_recipes', to='doctors.doctors')),
                ('region', models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.PROTECT, related_name='day_recipes', to='regions.region')),
            ],
            options={
                'db_table': 'day_recipes',
            },
        ),
        migrations.CreateModel(
            name='DayRecipeDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(db_column='drug_id', on_delete=django.db.models.deletion.PROTECT, related_name='day_recipe_drugs', to='medicine.medical')),
                ('recipe', models.ForeignKey(db_column='recipe_id', on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='vizit.dayrecipe')),
            ],
            options={
                'db_table': 'day_recipe_drugs',
            },
        ),
    ]
