# Generated by Django 5.2.3 on 2026-09-11 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizit', '0013_dayrecipe_dayrecipedrug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayrecipe',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_recipes', to='vizit.istifadeci'),
        ),
    ]
