# Generated by Django 5.2.3 on 2026-09-14 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_alter_region_region_type'),
        ('vizit', '0014_dayrecipe_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Həftə başlanğıcı (B.e.)')),
                ('menecer_name', models.CharField(blank=True, max_length=150, verbose_name='Menecer')),
                ('sedr_name', models.CharField(blank=True, max_length=150, verbose_name='İdarə heyətinin sədri')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_schedules', to='vizit.istifadeci')),
            ],
            options={
                'verbose_name': 'Həftəlik qrafiq',
                'verbose_name_plural': 'Həftəlik qrafiklər',
                'db_table': 'weekly_schedules',
                'ordering': ['-week_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Bazar ertəsi'), (2, 'Çərşənbə axşamı'), (3, 'Çərşənbə'), (4, 'Cümə axşamı'), (5, 'Cümə')])),
                ('qrafik', models.CharField(blank=True, max_length=150, verbose_name='Qrafik')),
                ('tn', models.CharField(blank=True, max_length=100, verbose_name='T/N')),
                ('region', models.ForeignKey(blank=True, db_column='region_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_schedule_days', to='regions.region', verbose_name='Bölgə')),
                ('schedule', models.ForeignKey(db_column='schedule_id', on_delete=django.db.models.deletion.CASCADE, related_name='days', to='vizit.weeklyschedule')),
            ],
            options={
                'verbose_name': 'Qrafik günü',
                'verbose_name_plural': 'Qrafik günləri',
                'db_table': 'weekly_schedule_days',
                'ordering': ['weekday'],
                'unique_together': {('schedule', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyScheduleVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255, verbose_name='Yer / klinika')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('day', models.ForeignKey(db_column='day_id', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='vizit.weeklyscheduleday')),
            ],
            options={
                'verbose_name': 'Qrafik viziti',
                'verbose_name_plural': 'Qrafik vizitləri',
                'db_table': 'weekly_schedule_visits',
                'ordering': ['position', 'id'],
            },
        ),
    ]
