# Generated by Django 5.2.3 on 2026-09-14 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_doctors_is_active'),
        ('regions', '0004_alter_region_region_type'),
        ('vizit', '0015_weekly_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='GorulenHekim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_date', models.DateField(verbose_name='Tarix')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('bolge', models.ForeignKey(db_column='bolge_id', on_delete=django.db.models.deletion.PROTECT, related_name='gorulen_hekimler', to='regions.region')),
                ('hekim', models.ForeignKey(db_column='hekim_id', on_delete=django.db.models.deletion.CASCADE, related_name='gorulme_qeydleri', to='doctors.doctors')),
                ('istifadeci', models.ForeignKey(db_column='istifadeci_id', on_delete=django.db.models.deletion.CASCADE, related_name='gorulen_hekimler', to='vizit.istifadeci')),
            ],
            options={
                'verbose_name': 'Görülən həkim',
                'verbose_name_plural': 'Görülən həkimlər',
                'db_table': 'gorulen_hekimler',
                'ordering': ['-seen_at'],
                'unique_together': {('istifadeci', 'hekim', 'seen_date')},
            },
        ),
    ]
