# Generated by Django 5.2.5 on 2025-09-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('fayl', models.FileField(upload_to='backups/')),
                ('olusturulma_tarixi', models.DateTimeField(auto_now_add=True)),
                ('olcu', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
