# Generated by Django 5.2.5 on 2025-09-11 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('medicine', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Avans', 'Avans'), ('İnvest', 'İnvestisiya'), ('Geri_qaytarma', 'Geri Qaytarma')], default='Avans', max_length=200)),
                ('pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.region')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odenisler', to='doctors.doctors')),
            ],
            options={
                'verbose_name': 'Həkimə Ödəniş',
                'verbose_name_plural': 'Həkimə Ödənişlər',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sale_date', models.DateField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='medicine.medical')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='regions.region')),
            ],
            options={
                'verbose_name': 'Bölgə Satış',
                'verbose_name_plural': 'Bölgə Satışları',
            },
        ),
        migrations.CreateModel(
            name='MonthlyDoctorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_month', models.DateField()),
                ('borc', models.FloatField(default=0)),
                ('avans', models.FloatField(default=0)),
                ('investisiya', models.FloatField(default=0)),
                ('hesablanan_miqdar', models.FloatField(default=0)),
                ('hekimden_silinen', models.FloatField(default=0)),
                ('yekun_borc', models.FloatField(default=0)),
                ('recipe_total_drugs', models.IntegerField(default=0)),
                ('recipe_drugs_list', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctors')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.region')),
            ],
            options={
                'unique_together': {('doctor', 'report_month')},
            },
        ),
    ]
