# Generated by Django 5.2.5 on 2025-10-14 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctors_razılaşma'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_photo', models.ImageField(upload_to='check_photos/')),
                ('check_date', models.DateField()),
                ('check_dr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctors')),
            ],
        ),
    ]
