# Generated by Django 5.2.5 on 2025-10-14 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_financial_document'),
        ('regions', '0002_alter_hospital_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial_document',
            name='check_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.region'),
        ),
    ]
