# Generated by Django 5.2.3 on 2025-11-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_financial_document_check_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_doctor',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
