# Generated by Django 5.2.3 on 2025-11-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_doctor_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydoctorreport',
            name='geriqaytarma',
            field=models.FloatField(default=0),
        ),
    ]
