# Generated by Django 5.2.3 on 2026-06-16 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_medical_position'),
        ('payment', '0005_monthlydoctorreport_geriqaytarma'),
        ('regions', '0004_alter_region_region_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepoSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depo_type', models.CharField(choices=[('Avromed', 'Avromed'), ('Zeytun', 'Zeytun'), ('Binə', 'Binə')], default='Avromed', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depo_sales', to='medicine.medical')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depo_sales', to='regions.region')),
            ],
            options={
                'verbose_name': 'Depo Satış',
                'verbose_name_plural': 'Depo Satışları',
            },
        ),
    ]
