# Generated by Django 5.2.3 on 2026-07-06 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0004_medical_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aptek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Aptek adı')),
                ('location', models.CharField(blank=True, default='', max_length=250)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Aptek',
                'verbose_name_plural': 'Apteklər',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Qaime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Qaimə №')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='qaimeler/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aptek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qaimeler', to='aptek.aptek')),
            ],
            options={
                'verbose_name': 'Qaimə',
                'verbose_name_plural': 'Qaimələr',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnbarHereket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Giriş'), ('out', 'Çıxış')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anbar_hereketleri', to='medicine.medical')),
                ('aptek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anbar_hereketleri', to='aptek.aptek')),
                ('qaime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hereketler', to='aptek.qaime')),
            ],
            options={
                'verbose_name': 'Anbar hərəkəti',
                'verbose_name_plural': 'Anbar hərəkətləri',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
