# Generated by Django 5.2.3 on 2026-07-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptek', '0003_add_missing_june_drugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aptek',
            name='location',
        ),
        migrations.RemoveField(
            model_name='aptek',
            name='note',
        ),
        migrations.RemoveField(
            model_name='aptek',
            name='phone',
        ),
    ]
