# Generated by Django 5.2.3 on 2026-07-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptek', '0004_remove_aptek_location_remove_aptek_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaime',
            name='document_type',
            field=models.CharField(choices=[('qaime', 'Qaimə'), ('geri_qaytarma', 'Geri qaytarma')], default='qaime', max_length=20, verbose_name='Sənəd növü'),
        ),
        migrations.AddConstraint(
            model_name='qaime',
            constraint=models.UniqueConstraint(fields=('aptek', 'number', 'document_type'), name='unique_aptek_qaime_number_type'),
        ),
    ]
