# Generated by Django 5.2.3 on 2026-07-17 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptek', '0009_alter_qaime_options_drugstock'),
        ('medicine', '0004_medical_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_prices', to='medicine.medical')),
            ],
            options={
                'verbose_name': 'Dərman qiyməti',
                'verbose_name_plural': 'Dərman qiymətləri',
                'ordering': ['-price'],
            },
        ),
        migrations.DeleteModel(
            name='DrugStock',
        ),
    ]
