# Generated by Django 5.2.3 on 2026-07-17 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptek', '0010_drugprice_delete_drugstock'),
        ('medicine', '0004_medical_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugprice',
            options={'ordering': ['drug__med_name'], 'verbose_name': 'Dərman qiyməti', 'verbose_name_plural': 'Dərman qiymətləri'},
        ),
        migrations.AddField(
            model_name='drugprice',
            name='category',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Kateqoriya'),
        ),
        migrations.AddField(
            model_name='drugprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='drugprice',
            name='depo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug_prices', to='aptek.depo', verbose_name='Anbar'),
        ),
        migrations.AddField(
            model_name='drugprice',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='SKT'),
        ),
        migrations.AddField(
            model_name='drugprice',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='Min. stok'),
        ),
        migrations.AlterField(
            model_name='drugprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymət'),
        ),
        migrations.AddConstraint(
            model_name='drugprice',
            constraint=models.UniqueConstraint(fields=('depo', 'drug'), name='unique_depo_drug_price'),
        ),
    ]
