# Generated by Django 5.2.3 on 2026-07-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptek', '0012_seed_drug_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugprice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='drugprice',
            name='min_stock',
        ),
    ]
