# Generated by Django 5.2.3 on 2026-07-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptek', '0013_remove_drugprice_category_remove_drugprice_min_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaime',
            name='is_official',
            field=models.BooleanField(default=False, verbose_name='Rəsmi'),
        ),
    ]
