# Generated by Django 5.2.3 on 2026-10-07 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptek', '0014_qaime_is_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='anbarhereket',
            name='transfer_depo',
            field=models.ForeignKey(blank=True, help_text='Bu hərəkətin başqa depo ilə əlaqəsini göstərir', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_hereketleri', to='aptek.depo', verbose_name='Transfer depo'),
        ),
        migrations.AddField(
            model_name='anbarhereket',
            name='transfer_ref',
            field=models.CharField(blank=True, default='', help_text='Anbarlar arası transfer üçün unikal identifikator', max_length=50, verbose_name='Transfer referens'),
        ),
    ]
