# Generated by Django 5.2.5 on 2025-09-11 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('ixtisas', models.CharField(choices=[('CA', 'CA'), ('TE', 'TE'), ('SU', 'SU'), ('TR', 'TR'), ('NE', 'NE'), ('PE', 'PE'), ('EN', 'EN'), ('GI', 'GI'), ('DE', 'DE'), ('OR', 'OR'), ('PS', 'PS'), ('UR', 'UR'), ('ON', 'ON'), ('RE', 'RE'), ('AL', 'AL')], max_length=100)),
                ('kategoriya', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10)),
                ('derece', models.CharField(choices=[('VIP', 'ViP Dərəcə'), ('I', 'I Dərəcə'), ('II', 'II Dərəcə'), ('III', 'III Dərəcə')], default='II', max_length=10)),
                ('cinsiyyet', models.CharField(choices=[('Kişi', 'Kişi'), ('Qadın', 'Qadın')], default='Kişi', max_length=10)),
                ('number', models.CharField(blank=True, max_length=250, null=True)),
                ('barkod', models.CharField(blank=True, max_length=10, unique=True)),
                ('avans', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('investisiya', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('geriqaytarma', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('previous_debt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hesablanan_miqdar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hekimden_silinen', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('datasiya', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('borc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('yekun_borc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bolge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='regions.region')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.city')),
                ('klinika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.hospital')),
            ],
            options={
                'verbose_name': 'Həkim',
                'verbose_name_plural': 'Həkimlər',
            },
        ),
        migrations.CreateModel(
            name='RealSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sale', models.DateField()),
                ('dr_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctors')),
                ('region_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.region')),
            ],
            options={
                'verbose_name': 'Real Satış',
                'verbose_name_plural': 'Real Satışlar',
            },
        ),
        migrations.CreateModel(
            name='RealSalesDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.PositiveIntegerField()),
                ('drug_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medical')),
                ('real_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_name', to='doctors.realsales')),
            ],
            options={
                'verbose_name': 'Real Satış Dərmanı',
                'verbose_name_plural': 'Real Satış Dərmanları',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='doctors.doctors')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.region')),
            ],
            options={
                'verbose_name': 'Resept',
                'verbose_name_plural': 'Reseptlər',
            },
        ),
        migrations.CreateModel(
            name='RecipeDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=1, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medical')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='doctors.recipe')),
            ],
            options={
                'verbose_name': 'Resept Dərmanı',
                'verbose_name_plural': 'Reseptdəki Dərmanlar',
            },
        ),
    ]
