# Generated by Django 5.2.5 on 2025-09-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='razılaşma',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
