# Generated by Django 5.2.5 on 2025-10-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctors_razılaşma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='avans',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='geriqaytarma',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='investisiya',
        ),
    ]
