# Generated by Django 5.2.5 on 2025-10-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_doctors_avans_remove_doctors_geriqaytarma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='avans',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctors',
            name='geriqaytarma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctors',
            name='investisiya',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
