# Generated by Django 5.2.3 on 2025-11-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctors_avans_doctors_geriqaytarma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='avans',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='geriqaytarma',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='investisiya',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='ixtisas',
            field=models.CharField(choices=[('CA', 'CA'), ('TE', 'TE'), ('SU', 'SU'), ('TR', 'TR'), ('NE', 'NE'), ('PE', 'PE'), ('EN', 'EN'), ('GN', 'GN'), ('DE', 'DE'), ('OR', 'OR'), ('PS', 'PS'), ('UR', 'UR'), ('ON', 'ON'), ('RE', 'RE'), ('AL', 'AL'), ('END', 'END'), ('GA', 'GA'), ('LOR', 'LOR'), ('DV', 'DV'), ('NP', 'NP')], max_length=100),
        ),
    ]
