# Generated by Django 5.2.3 on 2025-11-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_remove_doctors_avans_remove_doctors_geriqaytarma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='ixtisas',
            field=models.CharField(choices=[('CA', 'CA'), ('TE', 'TE'), ('SU', 'SU'), ('TR', 'TR'), ('NE', 'NE'), ('PE', 'PE'), ('EN', 'EN'), ('GN', 'GN'), ('DE', 'DE'), ('OR', 'OR'), ('PS', 'PS'), ('UR', 'UR'), ('ON', 'ON'), ('RE', 'RE'), ('AL', 'AL'), ('END', 'END'), ('GA', 'GA'), ('LOR', 'LOR'), ('DV', 'DV'), ('NP', 'NP'), ('AN', 'AN'), ('AN/UR', 'AN/UR'), ('BE', 'BE'), ('CU', 'CU'), ('DZ', 'DZ'), ('EN-DİA', 'EN-DİA'), ('EN-RN', 'EN-RN'), ('EN-Z', 'EN-Z'), ('FL', 'FL'), ('FT', 'FT'), ('FZ', 'FZ'), ('GAS', 'GAS'), ('GE', 'GE'), ('HE', 'HE'), ('IN', 'IN'), ('KA', 'KA'), ('NEF', 'NEF'), ('NP-C', 'NP-C'), ('OF', 'OF'), ('PE-TE', 'PE-TE'), ('PED', 'PED'), ('PU', 'PU'), ('PUL', 'PUL'), ('RA', 'RA'), ('RE-PE', 'RE-PE'), ('REV', 'REV'), ('RV', 'RV'), ('SU-TP', 'SU-TP'), ('TP', 'TP'), ('UR-AN', 'UR-AN'), ('URO', 'URO'), ('URO-AND', 'URO-AND'), ('İN', 'İN')], max_length=100),
        ),
    ]
