# Generated by Django 5.2.3 on 2025-12-16 05:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctors_ixtisas'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
