# Generated by Django 5.2.3 on 2026-03-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_doctors_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
