# Generated by Django 5.2.5 on 2025-09-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=250)),
                ('med_full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('med_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('komissiya', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dərman',
                'verbose_name_plural': 'Dərmanlar',
            },
        ),
    ]
