# Generated by Django 5.2.5 on 2025-09-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medical',
            table='medicine_medical',
        ),
    ]
