# Generated by Django 5.2.3 on 2026-05-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_alter_medical_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
