# Generated by Django 5.2.3 on 2026-06-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_medical_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
