# Generated by Django 5.2.5 on 2025-09-11 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movqe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tarix', models.DateTimeField(auto_now_add=True)),
                ('istifadeci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movqeler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tarix'],
            },
        ),
    ]
